### ISSUE TITLE
`sdk-js` refactor #1 (Must Have)

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-js#253]
Improvements (Must Have):
- [x] https://github.com/nevermined-io/sdk-js/issues/295
- [x] https://github.com/nevermined-io/sdk-js/issues/296
- [x] nevermined-io/sdk-js#254 
- [x] Marketplace API integration and JWT management (@dancespiele )
- [x] Update The Graph integration to support contracts 2.0 (@r-marques )
- [x] Unify errors management and code errors
- [x] Decide what documentation system used to write in code documentation JSDoc vs TSDoc
- [x] Add a better error handling management
- [x] nevermined-io/sdk-js#226 
- [x] nevermined-io/sdk-js#249 
- [x] https://github.com/nevermined-io/sdk-js/issues/265
- [x] The gas calculation in the `ContractsBase` should be refactor after `ethers` migration
- [x] https://github.com/nevermined-io/sdk-js/issues/313
- [x] https://github.com/nevermined-io/sdk-js/issues/309
- [x] https://github.com/nevermined-io/sdk-js/pull/306
- [x] https://github.com/nevermined-io/sdk-js/issues/308
- [x] See if we can replace truffle HDWallet provider with the one provided with ethers.js 
- [x] https://github.com/nevermined-io/sdk-js/pull/352
