### ISSUE TITLE
`sdk-js` refactor #2

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-js#262]
The goal of this epic is to gather in one place all the small non-critical modifications that we would like to see on the sdk to improve developer experience.

Must Have:
- [x] https://github.com/nevermined-io/sdk-js/issues/354
- [x] #363
- [x] #364
- [x] Evaluate refactor the API
- [x] #358
- [x] #374 
- [x] Remove unused code
- [x] Move to nigthly tests all the subgraph integration tests
- [x] Simplify architecture to reduce the number of layers/interfaces used (reduce the number of things to modify)
- [x] Refactor the SDK to have a more modular architecture (review when the architecture is simplified)
- [x] #415
- [x] #416
- [x] #435
