### ISSUE TITLE
SDK refactor and improvements (sdk v2)

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-js#546]
SDK v2 epic including the following tasks:

```[tasklist]
### Improvements
- [ ] https://github.com/nevermined-io/sdk-js/issues/567
- [ ] https://github.com/nevermined-io/sdk-js/issues/579
- [ ] https://github.com/nevermined-io/sdk-js/issues/557
- [ ] https://github.com/nevermined-io/sdk-js/issues/581
- [ ] https://github.com/nevermined-io/sdk-js/issues/404
- [ ] https://github.com/nevermined-io/one/issues/843
- [ ] https://github.com/nevermined-io/sdk-js/pull/573
- [ ] https://github.com/nevermined-io/sdk-js/pull/576
- [ ] https://github.com/nevermined-io/sdk-js/issues/552
- [ ] https://github.com/nevermined-io/sdk-js/issues/561
- [x] SDK Adaptation to Contracts 3.3.x
- [ ] https://github.com/nevermined-io/sdk-js/issues/529
- [ ] https://github.com/nevermined-io/sdk-js/issues/475
- [ ] https://github.com/nevermined-io/sdk-js/issues/537
- [ ] https://github.com/nevermined-io/sdk-js/issues/518
- [ ] https://github.com/nevermined-io/sdk-js/issues/476
- [x] Move compute tests to nightly
- [ ] https://github.com/nevermined-io/sdk-js/issues/554
- [ ] https://github.com/nevermined-io/sdk-js/issues/558
- [ ] https://github.com/nevermined-io/sdk-js/issues/562
- [ ] https://github.com/nevermined-io/sdk-js/issues/553
```
