### ISSUE TITLE
Migration of the sdk-js to `Viem`

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-js#640]
```[tasklist]
### Tasks
- [x] SDK internal refactor
- [x] Encapsulate BLockchain code into common class
- [x] Migrate code to Viem
- [x] Adapt unit tests
- [x] Adapt integration tests
- [x] Adapt the external tests
- [x] Migrate web3 clients from APIs
- [x] Adapt the way we do internal imports
- [x] Adapt the way we export components
```
